name: myvault
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.1
  provider: ^6.1.5
  go_router: ^16.2.0

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  image_picker: ^1.2.0
  file_picker: ^10.3.2
  path_provider: ^2.1.5
  intl: ^0.20.2

  syncfusion_flutter_pdfviewer: ^30.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true